version: '3.9'

services:
  user:
    build: ./users
    container_name: user-api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
  chat_with_llm:
    build: ./chat_with_llm
    container_name: chat-with-llm-api
    environment:
      PORT: 8000
    ports:
      - '8001:8000'
    restart: "no"
  login:
    build: ./login
    container_name: login
    environment:
      PORT: 8000
    ports:
      - '8002:8000'
    restart: "no"